import fs from 'node:fs/promises';
import path from 'node:path';
import type { Scene } from '@dcl/schemas';
import { shell } from 'electron';

import { type DependencyState, SortBy, type Project } from '/shared/types/projects';
import { PACKAGES_LIST } from '/shared/types/pkg';
import { DEFAULT_DEPENDENCY_UPDATE_STRATEGY } from '/shared/types/settings';
import type { Template, Workspace } from '/shared/types/workspace';

import { getConfig, setConfig } from './config';
import { exists, writeFile as deepWriteFile } from './fs';
import { hasDependency } from './pkg';
import { getRowsAndCols, parseCoords, updateSceneThumbnail } from './scene';
import { invoke } from './invoke';
import { getOudatedDeps } from './npm';
import { getDefaultScenesPath, getScenesPath } from './settings';
import { getScene } from './scene';

import { DEFAULT_THUMBNAIL, NEW_SCENE_NAME, EMPTY_SCENE_TEMPLATE_REPO } from './constants';
import { getWorkspaceConfigPath } from './editor';
import { getProjectId } from './analytics';

/**
 * Returns whether or not the provided directory is a decentraland project or not
 */
export async function isDCL(_path: string) {
  try {
    await getScene(_path);
    return hasDependency(_path, '@dcl/sdk');
  } catch (_) {
    return false;
  }
}

/**
 * Returns whether or not the provided directory is empty or not
 */
export async function isEmpty(_path: string) {
  try {
    const files = await fs.readdir(_path);
    return files.length === 0;
  } catch (_) {
    return false;
  }
}

/**
 * Return whether or not the provided directory has a node_modules directory
 */
export async function hasNodeModules(_path: string) {
  const nodeModulesPath = path.join(_path, 'node_modules');
  return exists(nodeModulesPath);
}

export async function getOldProjectThumbnailPath(_path: string) {
  const workspaceConfigPath = await getWorkspaceConfigPath(_path);
  return path.join(workspaceConfigPath, 'images', 'project-thumbnail.png');
}

export function getProjectThumbnailPath() {
  return path.join('assets', 'images', 'autogenerated-thumbnail.png');
}

export async function getProjectThumbnailAsBase64(
  projectPath: string,
  scene?: Scene,
): Promise<string> {
  try {
    scene = scene ?? (await getScene(projectPath));
    const thumbnailPath = path.join(projectPath, scene.display?.navmapThumbnail || '');
    return (await fs.readFile(thumbnailPath)).toString('base64');
  } catch (e) {
    try {
      // if there is no thumbnail defined in scene.json, look for the one inside assets/hub/
      const thumbnailPath = path.join(projectPath, getProjectThumbnailPath());
      return (await fs.readFile(thumbnailPath)).toString('base64');
    } catch (_) {
      try {
        // if there is no thumbnail in assets/hub/, look for old one inside .editor/
        const thumbnailPath = await getOldProjectThumbnailPath(projectPath);
        return (await fs.readFile(thumbnailPath)).toString('base64');
      } catch (e) {
        // if none of the above, return a default thumbnail...
        console.warn(`Could not get project thumbnail for project in ${projectPath}`, e);
        return DEFAULT_THUMBNAIL;
      }
    }
  }
}

export async function getOutdatedPackages(_path: string): Promise<DependencyState> {
  const outdated = await getOudatedDeps(_path, PACKAGES_LIST);
  return outdated as DependencyState;
}

export async function getProject(_path: string): Promise<Project> {
  try {
    const [id, scene, stat, dependencyAvailableUpdates] = await Promise.all([
      getProjectId(_path),
      getScene(_path),
      fs.stat(_path),
      getOutdatedPackages(_path),
    ]);
    const thumbnail = await getProjectThumbnailAsBase64(_path, scene);
    const layout = getRowsAndCols(scene.scene.parcels.map($ => parseCoords($)));

    return {
      id,
      path: _path,
      title: scene.display?.title || 'Untitled scene',
      description: scene.display?.description,
      thumbnail,
      layout,
      scene: scene.scene,
      createdAt: Number(stat.birthtime),
      updatedAt: Number(stat.mtime),
      size: stat.size,
      worldConfiguration: scene?.worldConfiguration,
      dependencyAvailableUpdates,
    };
  } catch (error: any) {
    throw new Error(`Could not get project in "${_path}": ${error.message}`);
  }
}

export async function getPath() {
  const appHome = await getScenesPath();
  try {
    await fs.stat(appHome);
  } catch (error) {
    await fs.mkdir(appHome);
  }
  return appHome;
}

/**
 * Returns all decentraland projects in the provided directories (or the default one if no provided)
 */
export async function getProjects(paths: string | string[]): Promise<[Project[], string[]]> {
  paths = Array.isArray(paths) ? paths : [paths];
  if (!paths.length) return [[], []];

  const promises: Promise<Project>[] = [];
  const missing: string[] = [];

  for (const _path of paths) {
    if (!(await exists(_path))) {
      // _path doesn't exist
      missing.push(_path);
    } else if (await isDCL(_path)) {
      // _path is a project
      promises.push(getProject(_path));
    } else {
      // _path is a directory with projects
      const files = await fs.readdir(_path);
      for (const dir of files) {
        try {
          const projectDir = path.join(_path, dir);
          if (await isDCL(projectDir)) {
            promises.push(getProject(projectDir));
          }
          // eslint-disable-next-line no-empty
        } catch (_) {}
      }
    }
  }

  const projects = await Promise.all(promises);
  return [projects, missing];
}

/**
 * Fetches a list of templates and filters them by scene type.
 * @returns {Promise<Template[]>} A promise that resolves to an array of Template objects.
 * @throws {Error} If the fetch request fails or if the response is not in the expected format.
 */
export async function getTemplates(): Promise<Template[]> {
  try {
    const response = await fetch('https://studios.decentraland.org/api/get/resources');
    const templates: Template[] = (await response.json()) as Template[];
    return templates.filter($ => $.scene_type?.includes('Scene template'));
  } catch (e) {
    console.warn('[Preload] Could not get templates', e);
    return [];
  }
}

/**
 * Returns workspace info
 */
export async function getWorkspace(): Promise<Workspace> {
  const config = await getConfig();
  const [[projects, missing], templates] = await Promise.all([
    getProjects(config.workspace.paths),
    getTemplates(),
  ]);

  return {
    sortBy: SortBy.NEWEST, // TODO: read from editor config file...
    projects,
    missing,
    templates,
    settings: {
      ...config.settings,
      // TODO: implement migrations for config file...
      dependencyUpdateStrategy:
        config.settings?.dependencyUpdateStrategy ?? DEFAULT_DEPENDENCY_UPDATE_STRATEGY,
      scenesPath: config.settings?.scenesPath ?? (await getDefaultScenesPath()),
    },
  };
}

export async function getAvailable(_name: string) {
  let availableName = _name;
  let counter = 2;
  const homePath = await getPath();
  let availablePath = path.join(homePath, availableName);
  while (await exists(availablePath)) {
    availableName = `${_name} ${counter++}`;
    availablePath = path.join(homePath, availableName);
  }
  return { name: availableName, path: availablePath };
}

/**
 * Creates a new project with the given options.
 *
 * This function generates a new project folder with a unique name (if a project with the same name already exists)
 * and initializes it using a specified repository template. It also updates the project’s `scene.json` file and
 * adds the project path to the user's workspace configuration.
 *
 * @param {Object} [opts] - Options for creating the project.
 * @param {string} [opts.name] - The desired name for the project. Defaults to a new scene name.
 * @param {string} [opts.repo] - The repository to use as the template. Defaults to an empty scene template repository.
 * @returns {Promise<Project>} - A promise that resolves to the created project.
 */
export async function createProject(opts?: { name?: string; repo?: string }): Promise<Project> {
  const { name, repo } = {
    name: opts?.name ?? NEW_SCENE_NAME,
    repo: opts?.repo ?? EMPTY_SCENE_TEMPLATE_REPO,
  };

  const available = await getAvailable(name);
  await fs.mkdir(available.path);
  await invoke('cli.init', available.path, repo);
  const scene = await getScene(available.path);
  scene.display!.title = available.name;
  // TODO: Fix: Remove worldConfiguration in the scene.json of the templates
  if (repo !== EMPTY_SCENE_TEMPLATE_REPO) {
    delete scene.worldConfiguration;
  }
  const sceneJsonPath = path.join(available.path, 'scene.json');
  await fs.writeFile(sceneJsonPath, JSON.stringify(scene, null, 2));
  const project = await getProject(available.path);
  await setConfig(config => config.workspace.paths.push(available.path));
  return project;
}

/**
 * Unlists a project directory from config.
 *
 * @param paths - The path or paths of the directories to be unlisted.
 * @returns A Promise that resolves when the directories have been unlisted.
 */
export async function unlistProjects(paths: string[]): Promise<void> {
  const pathSet = new Set(paths);
  await setConfig(
    ({ workspace }) => (workspace.paths = workspace.paths.filter($ => !pathSet.has($))),
  );
}

/**
 * Deletes a project directory and all its contents.
 *
 * @param _path - The path of the directory to be deleted.
 * @returns A Promise that resolves when the directory has been deleted.
 */
export async function deleteProject(_path: string): Promise<void> {
  await unlistProjects([_path]);
}

/**
 * Duplicates a project directory, creating a copy with a modified title.
 *
 * @param _path - The path of the directory to be duplicated.
 * @returns A Promise that resolves to the duplicated Project.
 */
export async function duplicateProject(_path: string): Promise<Project> {
  const scene = await getScene(_path);
  const available = await getAvailable(scene.display?.title || NEW_SCENE_NAME);

  await fs.cp(_path, available.path, { recursive: true });
  scene.display = { ...scene.display, title: available.name };
  await fs.writeFile(path.join(available.path, 'scene.json'), JSON.stringify(scene, null, 2));
  const project = await getProject(available.path);
  return project;
}

/**
 * Imports a project by allowing the user to select a directory.
 *
 * @returns A Promise that resolves to the imported project path.
 * @throws An error if the selected directory is not a valid project.
 */
export async function importProject(): Promise<Project | undefined> {
  const [projectPath] = await invoke('electron.showOpenDialog', {
    title: 'Import project',
    properties: ['openDirectory'],
  });

  const cancelled = !projectPath;

  if (cancelled) return undefined;

  const pathBaseName = path.basename(projectPath);
  const config = await getConfig();
  const [projects] = await getProjects(config.workspace.paths);
  const projectAlreadyExists = projects.find($ => $.path === projectPath);

  if (projectAlreadyExists) {
    throw new Error(`"${pathBaseName}" is already on the projects library`);
  }

  if (!(await isDCL(projectPath))) {
    throw new Error(`"${pathBaseName}" is not a valid project`);
  }

  // update workspace on config file with new path
  await setConfig(config => config.workspace.paths.push(projectPath));

  const project = getProject(projectPath);
  return project;
}

/**
 * Reimports a project by allowing the user to select a new directory for a project whose path was deleted or renamed.
 *
 * @param _path - The current path of the project that needs to be reimported.
 * @returns A Promise that resolves to the reimported Project object.
 * @throws An error if the selected directory is not a valid project.
 */
export async function reimportProject(_path: string): Promise<Project | undefined> {
  const project = await importProject();
  if (project) await unlistProjects([_path]);
  return project;
}

/**
 * Saves a base64-encoded thumbnail image for a project and updates the scene metadata
 * if the current thumbnail is missing or invalid.
 *
 * @param {Object} params - The parameters needed to save the thumbnail.
 * @param {string} params.path - The path to the project directory.
 * @param {string} params.thumbnail - The base64-encoded thumbnail image data.
 * @returns {Promise<void>} A promise that resolves if everything went ok.
 */
export async function saveThumbnail({
  path: _path,
  thumbnail,
}: {
  path: string;
  thumbnail: string;
}): Promise<void> {
  const scene = await getScene(_path);
  const thumbnailPath = getProjectThumbnailPath();
  const currentThumb = scene.display?.navmapThumbnail;
  await deepWriteFile(path.join(_path, thumbnailPath), thumbnail, { encoding: 'base64' });
  const shouldOverwrite = !currentThumb || !(await exists(path.join(_path, currentThumb)));
  if (shouldOverwrite) await updateSceneThumbnail(_path, thumbnailPath);
}

export async function openFolder(_path: string) {
  const error = await shell.openPath(_path);
  if (error) throw new Error(error);
}
