/**
 * Runtime hooks for asset-pack composites loaded on-demand (i.e. via the
 * SPAWN_ENTITY action). Covers:
 *
 *   1. `{assetPath}` substitution at composite-load time, so on-disk asset
 *      packs can keep their portable placeholder convention.
 *   2. ID pre-allocation + Trigger reference remap at spawn time, so the
 *      composite's `{self}` / `{self:component}` / `{entity:component}`
 *      placeholders resolve to live numeric IDs before initActions /
 *      initTriggers bind handlers.
 *
 * TODO(future PR — consolidate inspector duplication):
 *   The inspector's `add-asset/index.ts` reimplements `{assetPath}` substitution
 *   (per-component switch-case, ~60 lines) and ID alloc + trigger remap (lines
 *   218-253 + 362-375). Refactor the inspector to call into this module so the
 *   asset-pack conventions are defined in exactly one place. Material/
 *   videoTexture parsing and Nodes-tree updates stay inspector-side.
 */

import type { Entity, IEngine, SystemFn } from '@dcl/ecs';
import { type Composite, getCompositeRootComponent } from '@dcl/ecs';
import { getNextId } from './id';
import { ComponentName, getComponents } from './definitions';

// ─── Constants ──────────────────────────────────────────────────────────────

const ASSET_PATH_TOKEN = '{assetPath}';
const SELF_REF = /^\{self:(.+)\}$/;
const CROSS_ENTITY_REF = /^\{(\d+):(.+)\}$/;
const COMPONENTS_WITH_ID: readonly string[] = [
  ComponentName.ACTIONS,
  ComponentName.STATES,
  ComponentName.COUNTER,
];

// ─── ts-proto shape helpers ─────────────────────────────────────────────────
//
// `ComponentData` is generated by ts-proto with a discriminated union:
//   { data: { $case: 'json', json: T } | { $case: 'binary', binary: Uint8Array } | undefined }
// All three runtime concerns below read the JSON-shaped payload, so every
// access goes through `getJsonPayload`. If the upstream shape changes, this
// is the single update point.

type CompositeComponent = Composite.Definition['components'][number];
type ComponentDataEntry = ReturnType<CompositeComponent['data']['get']>;

function getJsonPayload<T = unknown>(componentData: ComponentDataEntry): T | undefined {
  if (componentData?.data?.$case !== 'json') return undefined;
  return componentData.data.json as T | undefined;
}

// ─── `{assetPath}` substitution ─────────────────────────────────────────────

function assetPathFrom(compositeSrc: string): string {
  const slash = compositeSrc.lastIndexOf('/');
  return slash >= 0 ? compositeSrc.substring(0, slash) : '';
}

/**
 * Replace `{assetPath}` with `replacement` in every string value reachable
 * from `value`, including strings nested inside stringified payloads
 * (e.g. `asset-packs::Actions[i].jsonPayload`). Mutates in place. Idempotent.
 */
function deepReplaceAssetPath(value: unknown, replacement: string): void {
  if (value === null || typeof value !== 'object') return;

  if (Array.isArray(value)) {
    for (let i = 0; i < value.length; i++) {
      const item = value[i];
      if (typeof item === 'string') {
        if (item.includes(ASSET_PATH_TOKEN)) {
          value[i] = item.split(ASSET_PATH_TOKEN).join(replacement);
        }
      } else {
        deepReplaceAssetPath(item, replacement);
      }
    }
    return;
  }

  const obj = value as Record<string, unknown>;
  for (const key of Object.keys(obj)) {
    const item = obj[key];
    if (typeof item === 'string') {
      if (item.includes(ASSET_PATH_TOKEN)) {
        obj[key] = item.split(ASSET_PATH_TOKEN).join(replacement);
      }
    } else {
      deepReplaceAssetPath(item, replacement);
    }
  }
}

function substituteAssetPathInComposite(
  composite: Composite.Definition,
  compositeSrc: string,
): void {
  const replacement = assetPathFrom(compositeSrc);
  for (const component of composite.components) {
    for (const [, componentData] of component.data) {
      const payload = getJsonPayload(componentData);
      if (payload !== undefined) deepReplaceAssetPath(payload, replacement);
    }
  }
}

// ─── Composite provider wrapper ─────────────────────────────────────────────

function wrapProvider(base: Composite.Provider): Composite.Provider {
  return {
    getCompositeOrNull: src => base.getCompositeOrNull(src),
    loadComposite: base.loadComposite
      ? async src => {
          const resource = await base.loadComposite!(src);
          // Mutate in place: the base provider caches the resource by
          // reference, so subsequent getCompositeOrNull(src) calls return
          // the already-resolved version. Substitution is idempotent —
          // safe on a composite that was previously resolved.
          substituteAssetPathInComposite(resource.composite, src);
          return resource;
        }
      : undefined,
  };
}

/**
 * Install an asset-pack-aware wrapper around the SDK's default Composite.Provider.
 *
 * Install is **deferred to the first system tick** because the auto-generated
 * scene entrypoint hoists `import * as entrypoint from <user-entry>` (which
 * triggers asset-packs init) BEFORE `import * as sdk from '@dcl/sdk'` (which
 * registers the SDK's provider). Querying `engine.getCompositeProvider()`
 * synchronously here would return null. A one-shot installer system at
 * priority Infinity runs after every module-init has completed and before
 * any other system runs on the first tick, so SPAWN_ENTITY cannot fire
 * before the wrap is in place.
 *
 * TODO: revisit if a future SDK version exposes a post-init hook.
 */
export function installAssetPackCompositeProvider(engine: IEngine): void {
  let installed = false;
  const installer: SystemFn = () => {
    if (installed) return;
    const base = engine.getCompositeProvider();
    if (!base) return; // SDK provider not yet set; retry next tick
    installed = true;
    engine.setCompositeProvider(wrapProvider(base));
    engine.removeSystem(installer);
  };
  engine.addSystem(installer, Infinity, 'asset-pack-composite-provider-install');
}

// ─── ID allocation + Trigger reference remap (spawn-time) ───────────────────

type IdMap = Map<string, number>;

function idKey(componentName: string, entityId: number): string {
  return `${componentName}:${entityId}`;
}

interface ParsedRef {
  componentName: string;
  entityId?: number; // undefined ⇒ resolve against the ref's own entity
}

function parsePlaceholderRef(ref: string): ParsedRef | null {
  const self = ref.match(SELF_REF);
  if (self) return { componentName: self[1] };
  const cross = ref.match(CROSS_ENTITY_REF);
  if (cross) return { componentName: cross[2], entityId: Number(cross[1]) };
  return null;
}

// Minimal structural shape we need from any id-bearing component definition.
// Actions / States / Counter all expose `getMutableOrNull(entity)` returning
// a value with `.id: number`, but their `value` field types diverge (Action[]
// vs string[] vs number) which makes them incompatible as a Record value
// type. We only ever read/write `.id`, so this narrow shape is enough.
type IdMutableComponent = {
  getMutableOrNull(entity: Entity): { id?: number } | null;
};

/**
 * For each composite component listed in COMPONENTS_WITH_ID whose payload
 * carries `id: '{self}'`, allocate a fresh numeric ID via `getNextId`,
 * write it onto the live spawned component, and return the mapping so
 * Trigger references can be remapped in a second pass.
 *
 * The engine looks up the component definition by name directly — no
 * parallel `name → component` table to maintain.
 */
function allocateIdsForSpawnedComponents(
  engine: IEngine,
  composite: Composite.Definition,
  spawnedEntityByCompositeId: Map<number, Entity>,
): IdMap {
  const ids: IdMap = new Map();
  for (const component of composite.components) {
    if (!COMPONENTS_WITH_ID.includes(component.name)) continue;
    const ComponentDef = engine.getComponentOrNull(component.name) as IdMutableComponent | null;
    if (!ComponentDef) continue;

    for (const [compositeEntityId, componentData] of component.data) {
      const payload = getJsonPayload<{ id?: unknown }>(componentData);
      if (!payload || `${payload.id}` !== '{self}') continue;

      const destEntity = spawnedEntityByCompositeId.get(compositeEntityId);
      if (destEntity === undefined) continue;

      const newId = getNextId(engine);
      ids.set(idKey(component.name, compositeEntityId), newId);
      const live = ComponentDef.getMutableOrNull(destEntity);
      if (live) live.id = newId;
    }
  }
  return ids;
}

/**
 * Rewrite Trigger `actions[].id` and `conditions[].id` placeholder strings
 * (`{self:Component}` / `{entity:Component}`) into the numeric IDs allocated
 * in the previous pass.
 */
function remapTriggerReferences(
  engine: IEngine,
  spawnedEntities: Iterable<[Entity, number]>,
  ids: IdMap,
): void {
  const { Triggers } = getComponents(engine);

  const resolve = (idRef: unknown, ownCompositeEntityId: number): unknown => {
    if (typeof idRef !== 'string') return idRef;
    const parsed = parsePlaceholderRef(idRef);
    if (!parsed) return idRef;
    const lookupEntityId = parsed.entityId ?? ownCompositeEntityId;
    return ids.get(idKey(parsed.componentName, lookupEntityId)) ?? idRef;
  };

  for (const [destEntity, compositeEntityId] of spawnedEntities) {
    const triggers = Triggers.getMutableOrNull(destEntity);
    if (!triggers) continue;
    for (const trigger of triggers.value) {
      if (trigger.conditions) {
        for (const condition of trigger.conditions) {
          (condition as { id: unknown }).id = resolve(condition.id, compositeEntityId);
        }
      }
      for (const action of trigger.actions) {
        (action as { id: unknown }).id = resolve(action.id, compositeEntityId);
      }
    }
  }
}

/**
 * After `engine.addEntityFromComposite` spawns a smart-item subtree, resolve
 * its placeholder IDs so handlers can fire:
 *
 *   1. Allocate fresh numeric IDs for Actions/States/Counter components whose
 *      composite-side id is the literal `{self}`.
 *   2. Rewrite Trigger `actions[].id` / `conditions[].id` placeholders to
 *      point at the newly-allocated numeric IDs.
 *
 * Mirrors the inspector's drag-n-drop initialization pass; both should
 * eventually call this function (see TODO at top of file).
 */
export function initializeComponentIdsFromComposite(
  engine: IEngine,
  composite: Composite.Definition,
  rootEntity: Entity,
): void {
  // The entity mapping was populated by instanceComposite on the rootEntity's
  // composite::root component — we read it back rather than threading it
  // through addEntityFromComposite's return value.
  const CompositeRoot = getCompositeRootComponent(engine);
  const root = CompositeRoot.getOrNull(rootEntity);
  if (!root) return;

  const spawnedEntityByCompositeId = new Map<number, Entity>();
  const inverse: [Entity, number][] = [];
  for (const e of root.entities) {
    spawnedEntityByCompositeId.set(e.src as number, e.dest);
    inverse.push([e.dest, e.src as number]);
  }

  const ids = allocateIdsForSpawnedComponents(engine, composite, spawnedEntityByCompositeId);
  remapTriggerReferences(engine, inverse, ids);
}
