/**
 * Runtime hooks for asset-pack composites loaded on-demand (i.e. via the
 * SPAWN_ENTITY action). Covers:
 *
 *   1. `{assetPath}` substitution at composite-load time, so on-disk asset
 *      packs can keep their portable placeholder convention.
 *   2. ID pre-allocation + Trigger reference remap at spawn time, so the
 *      composite's `{self}` / `{self:component}` / `{entity:component}`
 *      placeholders resolve to live numeric IDs before initActions /
 *      initTriggers bind handlers.
 *
 * Helpers exported here (`substituteAssetPathInComposite`,
 * `allocateIdsForSpawnedComponents`, `remapTriggerReferences`, `deepReplaceAssetPath`,
 * `getJsonPayload`) are the canonical implementations of asset-pack composite
 * conventions. Inspector add-asset and create-custom-asset operations consume
 * them. Material/videoTexture parsing and Nodes-tree updates stay inspector-side
 * — they touch editor-specific runtime state.
 */

import type { Entity, IEngine } from '@dcl/ecs';
import { type Composite } from '@dcl/ecs';
import { COMPONENTS_WITH_ID, getNextId, type EntityMap } from './mapping';
import { getComponents } from './definitions';

// ─── Constants ──────────────────────────────────────────────────────────────

const ASSET_PATH_TOKEN = '{assetPath}';
const SELF_REF = /^\{self:(.+)\}$/;
const CROSS_ENTITY_REF = /^\{(\d+):(.+)\}$/;

// ─── ts-proto shape helpers ─────────────────────────────────────────────────
//
// `ComponentData` is generated by ts-proto with a discriminated union:
//   { data: { $case: 'json', json: T } | { $case: 'binary', binary: Uint8Array } | undefined }
// All three runtime concerns below read the JSON-shaped payload, so every
// access goes through `getJsonPayload`. If the upstream shape changes, this
// is the single update point.

type CompositeComponent = Composite.Definition['components'][number];
type ComponentDataEntry = ReturnType<CompositeComponent['data']['get']>;

export function getJsonPayload<T = unknown>(componentData: ComponentDataEntry): T | undefined {
  if (componentData?.data?.$case !== 'json') return undefined;
  return componentData.data.json as T | undefined;
}

// ─── `{assetPath}` substitution ─────────────────────────────────────────────

// Inline POSIX-normalize. We can't import `path` here: `add-child.ts` is
// bundled into runtime scenes (sandboxed; no Node), and `path-browserify`
// is not a dependency. The normalizer walks segments, drops `.`, pops on
// `..`, and joins with `/` — matching `path.posix.normalize` for the
// substring shapes we feed it.
function normalizePosix(p: string): string {
  const segments = p.split('/');
  const out: string[] = [];
  for (const seg of segments) {
    if (seg === '' || seg === '.') continue;
    if (seg === '..') {
      if (out.length === 0 || out[out.length - 1] === '..') out.push('..');
      else out.pop();
      continue;
    }
    out.push(seg);
  }
  const prefix = p.startsWith('/') ? '/' : '';
  return prefix + out.join('/');
}

// Path-containment chokepoint for `{assetPath}` substitution. Given the
// post-substitution path candidate `joined` and the asset directory
// `replacement`, return the normalized `joined` if and only if
// POSIX-normalization keeps it inside `replacement` (equal to it or
// prefixed by `replacement + '/'`). Returns `null` for traversal payloads
// like `{assetPath}/../../etc/passwd`.
//
// Risky-API note: this is the single security primitive for the
// `{assetPath}` walker. Do not swap `normalizePosix` for a regex `..`
// blacklist — that rejects legitimate sibling paths.
function containAssetPath(replacement: string, joined: string): string | null {
  // No replacement (compositeSrc had no `/`): any traversal is suspicious
  // because the asset dir is the implicit cwd. Apply the same containment
  // logic against a `.` base.
  const base = replacement === '' ? '.' : normalizePosix(replacement);
  const normalized = normalizePosix(joined);
  if (normalized === base) return normalized;
  if (normalized.startsWith(base + '/')) return normalized;
  return null;
}

function assetPathFrom(compositeSrc: string): string {
  const slash = compositeSrc.lastIndexOf('/');
  return slash >= 0 ? compositeSrc.substring(0, slash) : '';
}

// Stringified-JSON carrier convention. Asset-packs Actions encode their
// per-action payload as a JSON-encoded string on the `jsonPayload` field
// (see `RESOURCE_ACTION_TYPES` in inspector/create-custom-asset). When the
// walker encounters this field, naïve string-level substitution would treat
// the whole JSON literal as a path candidate and `containAssetPath` would
// reject it (the string starts with `{`, not the asset dir), collapsing the
// payload to the bare replacement. Parse → recurse → re-serialize keeps the
// containment chokepoint intact for the actual path fields *inside* the
// payload.
//
// If a future component introduces a different stringified-JSON wrapper key,
// add the key here. Non-`jsonPayload` strings continue to flow through the
// plain path-substitution branch.
const JSON_WRAPPER_KEYS = new Set(['jsonPayload']);

/**
 * Replace `{assetPath}` with `replacement` in every string value reachable
 * from `value`, including strings nested inside stringified payloads
 * (e.g. `asset-packs::Actions[i].jsonPayload`). Mutates in place. Idempotent.
 *
 * Conventions for future contributors adding `{assetPath}`-bearing fields:
 *   - Plain path string at any depth: just works (structural recursion).
 *   - Stringified-JSON wrapper: name the field `jsonPayload` (or extend
 *     `JSON_WRAPPER_KEYS` above).
 *   - Avoid embedding `{assetPath}` inside larger non-path strings (URLs with
 *     query parameters etc.) — the containment check rejects those.
 */
export function deepReplaceAssetPath(value: unknown, replacement: string): void {
  if (value === null || typeof value !== 'object') return;

  const substitute = (raw: string): string => {
    const joined = raw.split(ASSET_PATH_TOKEN).join(replacement);
    // Strings that don't contain any path separator after substitution
    // can't traverse — skip the containment check for perf (e.g.
    // placeholders used as labels).
    if (!joined.includes('/') && !joined.includes('\\')) return joined;
    const contained = containAssetPath(replacement, joined);
    if (contained !== null) return contained;
    // Traversal detected. Log once and fall back to `replacement` itself,
    // which is at minimum syntactically inside the asset dir. Returning
    // the original `raw` would leave the unresolved `{assetPath}` token
    // in the output, breaking the runtime more visibly; returning the
    // bare `replacement` results in a 404-on-load that's easier to debug.
    // Use `console.error` (not `warn`): the SDK runtime `console` shim
    // exposes only `log` and `error`. Inspector / Node consumers still
    // surface this through their normal stderr.
    console.error(
      `[asset-packs] rejected {assetPath} substitution that escapes asset dir: ${JSON.stringify(raw)} -> ${JSON.stringify(joined)}`,
    );
    return replacement;
  };

  // Parse a stringified-JSON wrapper, recurse into the parsed value with the
  // same `replacement`, and re-serialize. Returns the new string on success
  // or `null` if the value is not a JSON object/array — callers fall back to
  // the plain path-substitution branch in that case.
  const substituteJsonWrapper = (raw: string): string | null => {
    // Cheap shape check before attempting parse — skips primitives, paths,
    // and labels that happen to live under a `jsonPayload` key.
    const first = raw.charCodeAt(0);
    if (first !== 0x7b /* '{' */ && first !== 0x5b /* '[' */) return null;
    let parsed: unknown;
    try {
      parsed = JSON.parse(raw);
    } catch {
      return null;
    }
    if (parsed === null || typeof parsed !== 'object') return null;
    deepReplaceAssetPath(parsed, replacement);
    return JSON.stringify(parsed);
  };

  if (Array.isArray(value)) {
    for (let i = 0; i < value.length; i++) {
      const item = value[i];
      if (typeof item === 'string') {
        if (item.includes(ASSET_PATH_TOKEN)) {
          value[i] = substitute(item);
        }
      } else {
        deepReplaceAssetPath(item, replacement);
      }
    }
    return;
  }

  const obj = value as Record<string, unknown>;
  for (const key of Object.keys(obj)) {
    const item = obj[key];
    if (typeof item === 'string') {
      if (JSON_WRAPPER_KEYS.has(key) && item.includes(ASSET_PATH_TOKEN)) {
        const next = substituteJsonWrapper(item);
        if (next !== null) {
          obj[key] = next;
          continue;
        }
      }
      if (item.includes(ASSET_PATH_TOKEN)) {
        obj[key] = substitute(item);
      }
    } else {
      deepReplaceAssetPath(item, replacement);
    }
  }
}

export function substituteAssetPathInComposite(
  composite: Composite.Definition,
  compositeSrc: string,
): void {
  const replacement = assetPathFrom(compositeSrc);
  for (const component of composite.components) {
    for (const [, componentData] of component.data) {
      const payload = getJsonPayload(componentData);
      if (payload !== undefined) deepReplaceAssetPath(payload, replacement);
    }
  }
}

// Component name prefixes to strip before instancing a spawned composite. Today
// this is editor-only metadata: the Inspector bakes `inspector::*` components
// (Config, Selection, Nodes, Hide, Lock, …) into authored composites for its own
// use. They carry no `jsonSchema`, are registered nowhere in the scene runtime,
// and are meaningless once deployed — so `Composite.instance` throws on them
// ("references undefined component"). Add further prefixes here if more need
// stripping.
const COMPONENTS_PREFIXES = ['inspector::'];

/**
 * Return a composite with every component whose name matches a
 * `COMPONENTS_PREFIXES` entry removed.
 *
 * Pure: returns the same reference when there is nothing to strip (so callers can
 * cheaply detect a no-op and avoid copying), otherwise a shallow copy with a
 * filtered `components` array. Entities are untouched — only the stripped
 * components attached to them are dropped, so entity mapping and ID remap are
 * unaffected.
 */
export function stripComponents(composite: Composite.Definition): Composite.Definition {
  const kept = composite.components.filter(
    c => !COMPONENTS_PREFIXES.some(prefix => c.name.startsWith(prefix)),
  );
  if (kept.length === composite.components.length) return composite;
  return { ...composite, components: kept };
}

// ─── ID allocation + Trigger reference remap (spawn-time) ───────────────────

type IdMap = Map<string, number>;

function idKey(componentName: string, entityId: number): string {
  return `${componentName}:${entityId}`;
}

interface ParsedRef {
  componentName: string;
  entityId?: number; // undefined ⇒ resolve against the ref's own entity
}

function parsePlaceholderRef(ref: string): ParsedRef | null {
  const self = ref.match(SELF_REF);
  if (self) return { componentName: self[1] };
  const cross = ref.match(CROSS_ENTITY_REF);
  if (cross) return { componentName: cross[2], entityId: Number(cross[1]) };
  return null;
}

// Minimal structural shape we need from any id-bearing component definition.
// Actions / States / Counter all expose `getMutableOrNull(entity)` returning
// a value with `.id: number`, but their `value` field types diverge (Action[]
// vs string[] vs number) which makes them incompatible as a Record value
// type. We only ever read/write `.id`, so this narrow shape is enough.
type IdMutableComponent = {
  getMutableOrNull(entity: Entity): { id?: number } | null;
};

/**
 * For each composite component listed in COMPONENTS_WITH_ID whose payload
 * carries `id: '{self}'`, allocate a fresh numeric ID via `getNextId`,
 * write it onto the live spawned component, and return the mapping so
 * Trigger references can be remapped in a second pass.
 *
 * The engine looks up the component definition by name directly — no
 * parallel `name → component` table to maintain.
 */
export function allocateIdsForSpawnedComponents(
  engine: IEngine,
  composite: Composite.Definition,
  spawnedEntityByCompositeId: Map<number, Entity>,
): IdMap {
  const ids: IdMap = new Map();
  for (const component of composite.components) {
    if (!COMPONENTS_WITH_ID.includes(component.name)) continue;
    const ComponentDef = engine.getComponentOrNull(component.name) as IdMutableComponent | null;
    if (!ComponentDef) continue;

    for (const [compositeEntityId, componentData] of component.data) {
      const payload = getJsonPayload<{ id?: unknown }>(componentData);
      if (!payload || `${payload.id}` !== '{self}') continue;

      const destEntity = spawnedEntityByCompositeId.get(compositeEntityId);
      if (destEntity === undefined) continue;

      const newId = getNextId(engine);
      ids.set(idKey(component.name, compositeEntityId), newId);
      const live = ComponentDef.getMutableOrNull(destEntity);
      if (live) live.id = newId;
    }
  }
  return ids;
}

/**
 * Rewrite Trigger `actions[].id` and `conditions[].id` placeholder strings
 * (`{self:Component}` / `{entity:Component}`) into the numeric IDs allocated
 * in the previous pass.
 */
export function remapTriggerReferences(
  engine: IEngine,
  spawnedEntities: Iterable<[Entity, number]>,
  ids: IdMap,
): void {
  const { Triggers } = getComponents(engine);

  const resolve = (idRef: unknown, ownCompositeEntityId: number): unknown => {
    if (typeof idRef !== 'string') return idRef;
    const parsed = parsePlaceholderRef(idRef);
    if (!parsed) return idRef;
    const lookupEntityId = parsed.entityId ?? ownCompositeEntityId;
    return ids.get(idKey(parsed.componentName, lookupEntityId)) ?? idRef;
  };

  for (const [destEntity, compositeEntityId] of spawnedEntities) {
    const triggers = Triggers.getMutableOrNull(destEntity);
    if (!triggers) continue;
    for (const trigger of triggers.value) {
      if (trigger.conditions) {
        for (const condition of trigger.conditions) {
          (condition as { id: unknown }).id = resolve(condition.id, compositeEntityId);
        }
      }
      for (const action of trigger.actions) {
        (action as { id: unknown }).id = resolve(action.id, compositeEntityId);
      }
    }
  }
}

/**
 * After `Composite.instance` spawns a smart-item subtree, resolve its
 * placeholder IDs so handlers can fire:
 *
 *   1. Allocate fresh numeric IDs for Actions/States/Counter components whose
 *      composite-side id is the literal `{self}`.
 *   2. Rewrite Trigger `actions[].id` / `conditions[].id` placeholders to
 *      point at the newly-allocated numeric IDs.
 *
 * The caller supplies the composite-entity → live-entity map directly (via
 * the `EntityMap` populated by `EMM_DIRECT_MAPPING`). We no longer read it
 * back from `CompositeRoot`: the new SDK only writes that component for
 * composites containing nested children, so leaf composites have no row to
 * read.
 *
 * Mirrors the inspector's drag-n-drop initialization pass; both should
 * eventually call this function (see TODO at top of file).
 */
export function initializeComponentIdsFromComposite(
  engine: IEngine,
  composite: Composite.Definition,
  entityMap: EntityMap,
): void {
  const spawnedEntityByCompositeId = new Map<number, Entity>();
  const inverse: [Entity, number][] = [];
  for (const [src, dst] of entityMap.entries()) {
    spawnedEntityByCompositeId.set(src as number, dst);
    inverse.push([dst, src as number]);
  }

  const ids = allocateIdsForSpawnedComponents(engine, composite, spawnedEntityByCompositeId);
  remapTriggerReferences(engine, inverse, ids);
}
