import React, { useCallback, useState, useMemo, useRef } from 'react';
import { MdImageSearch } from 'react-icons/md';
import { HiOutlinePlus } from 'react-icons/hi';
import { HiOutlineRefresh as RefreshIcon } from 'react-icons/hi';
import { IoIosFolderOpen } from 'react-icons/io';
import cx from 'classnames';
import { type AssetPack, catalog, isSmart } from '../../lib/logic/catalog';
import { getConfig } from '../../lib/logic/config';
import { getSceneClient } from '../../lib/rpc/scene';
import { useAppDispatch, useAppSelector } from '../../redux/hooks';
import {
  selectAssetToRename,
  selectStagedCustomAsset,
  getAssetCatalog,
} from '../../redux/data-layer';
import { getSelectedAssetsTab, selectAssetsTab } from '../../redux/ui';
import { AssetsTab } from '../../redux/ui/types';
import { useScanAssets } from '../../hooks/useScanAssets';
import { FolderOpen } from '../Icons/Folder';
import CleanupIcon from '../Icons/Cleanup';
import { AssetsCatalog } from '../AssetsCatalog';
import { ProjectAssetExplorer } from '../ProjectAssetExplorer';
import ImportAsset from '../ImportAsset';
import { CustomAssets } from '../CustomAssets';
import { selectCustomAssets } from '../../redux/app';
import { RenameAsset } from '../RenameAsset';
import { CreateCustomAsset } from '../CreateCustomAsset';
import { CleanAssets } from '../CleanAssets';
import type { InputRef } from '../FileInput/FileInput';
import { Button } from '../Button';
import { InfoTooltip } from '../ui';

import './Assets.css';

function removeSmartItems(assetPack: AssetPack) {
  return {
    ...assetPack,
    assets: assetPack.assets.filter(asset => !isSmart(asset)),
  };
}

function Assets({ isAssetsPanelCollapsed }: { isAssetsPanelCollapsed: boolean }) {
  const dispatch = useAppDispatch();
  const tab = useAppSelector(getSelectedAssetsTab);
  const customAssets = useAppSelector(selectCustomAssets);
  const [showCleanAssetsModal, setShowCleanAssetsModal] = useState(false);
  const [selectedCleanAssets, setSelectedCleanAssets] = useState<Set<string>>(new Set());

  const inputRef = useRef<InputRef>(null);

  const {
    assets: cleanAssets,
    isScanning,
    scanAssets,
  } = useScanAssets([
    'main.composite',
    'assets/composite.json',
    'assets/images/autogenerated-thumbnail.png',
  ]);

  const handleTabClick = useCallback(
    (tab: AssetsTab) => () => {
      dispatch(selectAssetsTab({ tab }));
    },
    [],
  );

  const config = getConfig();
  const filteredCatalog = config.disableSmartItems
    ? catalog.map(removeSmartItems).filter(assetPack => assetPack.assets.length > 0)
    : catalog;

  const assetToRename = useAppSelector(selectAssetToRename);
  const stagedCustomAsset = useAppSelector(selectStagedCustomAsset);

  const handleImportClick = useCallback(() => {
    inputRef.current?.onClick();
  }, [inputRef]);

  const handleRefreshClick = useCallback(() => {
    dispatch(getAssetCatalog());
  }, [dispatch]);

  const handleScanAssets = useCallback(async () => {
    const assets = await scanAssets();
    const selectedAssets = new Set<string>(
      assets.filter(asset => asset.unused).map(asset => asset.path),
    );
    setSelectedCleanAssets(selectedAssets);
  }, [scanAssets]);

  const handleCleanAssetsClick = useCallback(async () => {
    setShowCleanAssetsModal(true);
    handleScanAssets();
  }, [handleScanAssets]);

  const handleCloseCleanAssetsModal = useCallback(() => {
    setSelectedCleanAssets(new Set());
    setShowCleanAssetsModal(false);
  }, []);

  const handleSelectCleanAsset = useCallback((value: string) => {
    setSelectedCleanAssets(prevSet => {
      const isSelected = prevSet.has(value);
      const newSet = new Set(prevSet);
      if (isSelected) newSet.delete(value);
      else newSet.add(value);
      return newSet;
    });
  }, []);

  const handleOpenInExplorer = useCallback(async () => {
    try {
      const sceneClient = getSceneClient();
      if (!sceneClient) return;

      const path = tab === AssetsTab.CustomAssets ? 'custom' : '.';
      await sceneClient.openDirectory(path);
    } catch (error) {
      console.error('Failed to open folder:', error);
    }
  }, [tab]);

  const showCleanAssetsButton = useMemo(() => tab === AssetsTab.FileSystem, [tab]);
  const showOpenInExplorerButton = useMemo(() => {
    return (
      config.dataLayerRpcParentUrl &&
      (tab === AssetsTab.FileSystem || tab === AssetsTab.CustomAssets)
    );
  }, [tab, config.dataLayerRpcParentUrl]);
  const openInExplorerTooltipText = useMemo(() => {
    const text = tab === AssetsTab.CustomAssets ? 'custom items' : 'scene';
    return `Open ${text} folder in Explorer`;
  }, [tab]);

  return (
    <div className="Assets">
      <div className="Assets-buttons">
        <div className="Assets-buttons-left">
          <Button
            className="import-button"
            onClick={handleImportClick}
          >
            <HiOutlinePlus />
            IMPORT ASSETS
          </Button>
          <InfoTooltip
            text="Refresh assets"
            trigger={
              <RefreshIcon
                className="icon-item"
                onClick={handleRefreshClick}
              />
            }
            openOnTriggerMouseEnter={true}
            closeOnTriggerClick={true}
            position="top center"
          />
          {showOpenInExplorerButton && (
            <InfoTooltip
              text={openInExplorerTooltipText}
              trigger={
                <IoIosFolderOpen
                  className="icon-item"
                  onClick={handleOpenInExplorer}
                />
              }
              openOnTriggerMouseEnter={true}
              closeOnTriggerClick={true}
              position="top center"
            />
          )}
          {showCleanAssetsButton && (
            <InfoTooltip
              text="Clean unused assets"
              trigger={
                <button
                  className="icon-item"
                  onClick={handleCleanAssetsClick}
                >
                  <CleanupIcon />
                </button>
              }
              openOnTriggerMouseEnter={true}
              closeOnTriggerClick={true}
              position="top center"
            />
          )}
        </div>
        <div
          className="tab"
          onClick={handleTabClick(AssetsTab.FileSystem)}
          data-test-id={AssetsTab.FileSystem}
        >
          <div className={cx({ underlined: tab === AssetsTab.FileSystem })}>
            <FolderOpen />
            <span>LOCAL ASSETS</span>
          </div>
        </div>
        <div
          className="tab"
          onClick={handleTabClick(AssetsTab.CustomAssets)}
          data-test-id={AssetsTab.CustomAssets}
        >
          <div className={cx({ underlined: tab === AssetsTab.CustomAssets })}>
            <i className="icon-custom-assets" />
            <span>CUSTOM ITEMS</span>
          </div>
        </div>
        <div
          className="tab"
          onClick={handleTabClick(AssetsTab.AssetsPack)}
          data-test-id={AssetsTab.AssetsPack}
        >
          <div className={cx({ underlined: tab === AssetsTab.AssetsPack })}>
            <MdImageSearch />
            <span>ASSET PACKS</span>
          </div>
        </div>
      </div>
      <ImportAsset
        onSave={handleTabClick(AssetsTab.FileSystem)}
        ref={inputRef}
      >
        <div className={cx('Assets-content', { Hide: isAssetsPanelCollapsed })}>
          {tab === AssetsTab.AssetsPack && <AssetsCatalog catalog={filteredCatalog} />}
          {tab === AssetsTab.FileSystem && <ProjectAssetExplorer />}
          {tab === AssetsTab.CustomAssets && <CustomAssets />}
          {tab === AssetsTab.RenameAsset && assetToRename && (
            <RenameAsset
              assetId={assetToRename.id}
              currentName={assetToRename.name}
            />
          )}
          {tab === AssetsTab.CreateCustomAsset && stagedCustomAsset && <CreateCustomAsset />}
        </div>
      </ImportAsset>
      <CleanAssets
        isOpen={showCleanAssetsModal}
        assets={cleanAssets}
        isScanning={isScanning}
        selectedAssets={selectedCleanAssets}
        onClose={handleCloseCleanAssetsModal}
        onScan={handleScanAssets}
        onSelect={handleSelectCleanAsset}
      />
    </div>
  );
}

export default React.memo(Assets);
