/**
 * File-per-root codegen: each UI root is its own component file
 * (src/ui/<Name>.tsx) with a typed `state` binding surface, and a generated
 * src/ui/index.tsx composes them into setupUi(). Consumed by code/store.ts.
 *
 * @module
 */

/** Screen area a top-level root is placed in (react-ecs `UiScreenInset`). */
export type UiScreenInset = 'device' | 'interactable' | 'none';

export const DEFAULT_SCREEN_INSET: UiScreenInset = 'device';

const INSET_WRAPPER: Record<UiScreenInset, string | null> = {
  device: 'ScreenInsetArea',
  interactable: 'InteractableArea',
  none: null,
};

export interface UiRoot {
  component: string;
  from: string;
  screenInset?: UiScreenInset;
}

/** Recover each root's screen inset from an existing aggregator, keyed by component name. */
export function readRootInsets(source: string): Record<string, UiScreenInset> {
  const insets: Record<string, UiScreenInset> = {};
  const wrapped = /<(ScreenInsetArea|InteractableArea)>\s*<([A-Za-z_]\w*)\s*\/>\s*<\/\1>/g;
  for (const m of source.matchAll(wrapped)) {
    insets[m[2]] = m[1] === 'ScreenInsetArea' ? 'device' : 'interactable';
  }
  const insetAware = source.includes('ScreenInsetArea') || source.includes('InteractableArea');
  if (insetAware) {
    for (const m of source.matchAll(/<([A-Za-z_]\w*)\s*\/>/g)) {
      if (!(m[1] in insets)) insets[m[1]] = 'none';
    }
  }
  return insets;
}

/** Generate the ui/index.tsx aggregator wiring every top-level root (in its inset wrapper) to setUiRenderer. */
export function generateUiIndex(roots: UiRoot[]): string {
  const VALID = /^[A-Za-z_][A-Za-z0-9_]*$/;
  const safeRoots = roots.filter(r => {
    if (VALID.test(r.component)) return true;
    console.warn('[code-mode] skipping root with non-identifier component name', r.component);
    return false;
  });
  const imports = safeRoots.map(r => `import { ${r.component} } from '${r.from}'`).join('\n');
  const insetOf = (r: UiRoot): UiScreenInset => r.screenInset ?? DEFAULT_SCREEN_INSET;
  const children = safeRoots
    .map(r => {
      const tag = INSET_WRAPPER[insetOf(r)];
      return tag
        ? `      <${tag}>\n        <${r.component} />\n      </${tag}>`
        : `      <${r.component} />`;
    })
    .join('\n');
  const insetImports = (['ScreenInsetArea', 'InteractableArea'] as const).filter(tag =>
    safeRoots.some(r => INSET_WRAPPER[insetOf(r)] === tag),
  );
  const namedImports = ['UiEntity', 'ReactEcsRenderer', ...insetImports].join(', ');
  return `/** @jsx ReactEcs.createElement */
import ReactEcs, { ${namedImports} } from '@dcl/sdk/react-ecs'
${imports}

export function setupUi() {
  ReactEcsRenderer.setUiRenderer(() => (
    <UiEntity uiTransform={{ width: '100%', height: '100%' }}>
${children}
    </UiEntity>
  ))
}
`;
}

/** Source of the scene-local `useInteraction` helper, written into src/ui/interaction.tsx the first time a node gains interaction states. */
export function generateInteractionHelper(): string {
  return `// Generated by the Creator Hub UI editor — interaction-state styling.
//
// react-ecs has no native hover/press styling, so this helper layers style
// objects and tracks the pointer state that selects them:
//   base -> active -> hover -> press   (later layers win)
// Layers are deep-merged, so a layer may override a single nested field (just
// uiBackground.color) without dropping its siblings. Event handlers declared in
// a layer still fire — they are chained after the state trackers, not replaced.
//
// This is plain react-ecs and safe to hand-edit; the editor reads this shape
// back out of your UI files.
import ReactEcs from '@dcl/sdk/react-ecs'
import type { EntityPropTypes, UiLabelProps } from '@dcl/sdk/react-ecs'

// The known props are typed for autocomplete; the open index signature keeps
// element-specific props (an Input's placeholder, a Dropdown's options) from
// erroring in a strict scene tsconfig without intersecting three prop types
// whose onChange signatures conflict.
export type InteractionLayer = EntityPropTypes & Partial<UiLabelProps> & Record<string, unknown>

export interface InteractionLayers<T extends InteractionLayer = InteractionLayer> {
  // Generic in the BASE layer so the return type keeps its required props: a
  // Label's \`value\` is required by UiLabelProps, and once it lives in the base
  // layer only a \`T\`-shaped return satisfies \`<Label {...styles} />\`. The
  // override layers stay loosely typed — they are partial by nature.
  base?: T
  hover?: InteractionLayer
  press?: InteractionLayer
  active?: InteractionLayer
}

type Bag = Record<string, unknown>

function isPlainObject(value: unknown): value is Bag {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

function merge(base: Bag, over: Bag | undefined): Bag {
  if (!over) return base
  const out: Bag = { ...base }
  for (const key in over) {
    const next = over[key]
    const prev = out[key]
    out[key] = isPlainObject(next) && isPlainObject(prev) ? merge(prev, next) : next
  }
  return out
}

const chain =
  (track: () => void, own: (() => void) | undefined) =>
  () => {
    track()
    own?.()
  }

export function useInteraction<T extends InteractionLayer = InteractionLayer>(
  layers: InteractionLayers<T>,
  active?: boolean,
): T {
  const [hovered, setHovered] = ReactEcs.useState(false)
  const [pressed, setPressed] = ReactEcs.useState(false)

  let bag: Bag = (layers.base ?? {}) as Bag
  if (active) bag = merge(bag, layers.active as Bag | undefined)
  if (hovered) bag = merge(bag, layers.hover as Bag | undefined)
  if (pressed) bag = merge(bag, layers.press as Bag | undefined)

  const style = bag as InteractionLayer
  // The merge is dynamic, so the T-shaped result is asserted: every key of the
  // base layer survives it (overrides only replace values, never delete keys).
  return {
    ...style,
    onMouseEnter: chain(() => setHovered(true), style.onMouseEnter),
    onMouseLeave: chain(() => {
      setHovered(false)
      setPressed(false)
    }, style.onMouseLeave),
    onMouseDown: chain(() => setPressed(true), style.onMouseDown),
    onMouseUp: chain(() => setPressed(false), style.onMouseUp),
  } as T
}
`;
}

/** Source of the scene-local `usePlatform` helper, written into src/ui/platform.tsx the first time a node gains device variants. */
export function generatePlatformHelper(): string {
  return `// Generated by the Creator Hub UI editor — platform (device) variants.
//
// The explorer reports the platform asynchronously, so this reads 'desktop' for
// the first few frames; react-ecs re-renders every tick, so the UI switches as
// soon as it resolves. 'web' counts as desktop.
//
// This is plain SDK code and safe to hand-edit; the editor reads this shape back
// out of your UI files.
import { isMobile } from '@dcl/sdk/platform'

export type UiPlatform = 'desktop' | 'mobile'

export function usePlatform(): UiPlatform {
  return isMobile() ? 'mobile' : 'desktop'
}
`;
}

/** Source of a starter root component file for a newly created root — an empty component (a plain `return`, no elements). */
export function generateRootComponent(component: string): string {
  return `/** @jsx ReactEcs.createElement */
import ReactEcs from '@dcl/sdk/react-ecs'

export interface State {}
export const state: State = {}

export function ${component}(props: {}) {
  return
}
`;
}
