name: Get Latest Release
description: Get the latest GitHub release matching a regex pattern

inputs:
  repo:
    description: Repository in owner/repo format
    required: false
  pattern:
    description: Regex pattern for tag names
    default: '^[0-9]+\.[0-9]+\.[0-9]+$'
  prerelease:
    description: Allow prereleases (true/false)
    default: 'false'
  limit:
    description: Number of releases to fetch
    default: '100'

outputs:
  tag:
    description: Latest matching tag

runs:
  using: composite
  steps:
    - name: Get latest matching release
      id: latest
      shell: bash
      run: |
        REPO="${{ inputs.repo || github.repository }}"
        PATTERN="${{ inputs.pattern }}"
        ALLOW_PRERELEASE="${{ inputs.prerelease }}"
        LIMIT="${{ inputs.limit }}"

        LATEST_TAG=$(
          gh release list \
            --repo "$REPO" \
            --limit "$LIMIT" \
            --json tagName,isPrerelease \
            --jq ".[] | select(.isPrerelease == false or $ALLOW_PRERELEASE == \"true\") | .tagName" |
          grep -E "$PATTERN" |
          head -n 1
        )

        if [[ -z "$LATEST_TAG" ]]; then
          echo "❌ No matching releases found for pattern: $PATTERN"
          exit 1
        fi

        echo "Found latest matching release: $LATEST_TAG"
        echo "tag=$LATEST_TAG" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
