import type { FileSystemInterface } from '../../types';
import { DIRECTORY, getFilesInDirectory, withAssetDir } from '../fs-utils';

export const CUSTOM_ITEMS_GEN_PATH = 'src/custom-items.gen.ts';

interface CustomItemEntry {
  /** Sanitized TypeScript identifier, e.g. "My_Monster" */
  identifier: string;
  /** Display name from data.json, e.g. "My Monster" */
  displayName: string;
  /** Unique item id from data.json */
  id: string;
  /** Parsed composite with {assetPath} already replaced by the actual folder path */
  composite: unknown;
}

/**
 * Convert a display name to a valid TypeScript identifier.
 * Replaces non-alphanumeric characters with underscores and
 * prepends an underscore when the name starts with a digit.
 */
function toIdentifier(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9_]/g, '_')
    .replace(/^([0-9])/, '_$1');
}

/**
 * Read all Custom Items from the scene's assets/custom/ directory and
 * return structured entries ready for code generation.
 */
async function readCustomItems(
  fs: FileSystemInterface,
  customDir: string,
): Promise<CustomItemEntry[]> {
  const allPaths = await getFilesInDirectory(fs, customDir, [], true);
  // Collect unique top-level folder names (e.g. "monster_1", "chest_2")
  const slugs = [...new Set(allPaths.map(p => p.split('/')[1]).filter(Boolean))];

  const entries: CustomItemEntry[] = [];

  for (const slug of slugs) {
    const dataPath = `${customDir}/${slug}/data.json`;
    const compositePath = `${customDir}/${slug}/composite.json`;

    if (!(await fs.existFile(dataPath)) || !(await fs.existFile(compositePath))) {
      continue;
    }

    try {
      const dataRaw = await fs.readFile(dataPath);
      const compositeRaw = await fs.readFile(compositePath);

      const data = JSON.parse(new TextDecoder().decode(dataRaw)) as {
        id: string;
        name: string;
      };

      // Pre-resolve {assetPath} → the actual relative path of this item's folder
      const assetFolderPath = `${withAssetDir(DIRECTORY.CUSTOM)}/${slug}`;
      const compositeJson = new TextDecoder()
        .decode(compositeRaw)
        .replace(/\{assetPath\}/g, assetFolderPath);

      const composite = JSON.parse(compositeJson);

      entries.push({
        identifier: toIdentifier(data.name),
        displayName: data.name,
        id: data.id,
        composite,
      });
    } catch (err) {
      console.warn(`generateCustomItemsFile: failed to read custom item "${slug}":`, err);
    }
  }

  // Deduplicate identifiers (e.g. "My Monster" and "My_Monster" both → "My_Monster")
  const seen = new Map<string, number>();
  for (const entry of entries) {
    const base = entry.identifier;
    const count = seen.get(base) ?? 0;
    seen.set(base, count + 1);
    if (count > 0) {
      entry.identifier = `${base}_${count}`;
    }
  }

  // Sort for deterministic output
  entries.sort((a, b) => a.displayName.localeCompare(b.displayName));

  return entries;
}

/**
 * Generate the content of `src/custom-items.gen.ts`.
 */
function buildFileContent(entries: CustomItemEntry[]): string {
  const lines: string[] = [];

  lines.push(
    '// Auto-generated by the Decentraland Creator Hub. Do not edit manually.',
    '// This file is regenerated whenever you create, rename, or delete Custom Items.',
    '// Commit this file to version control.',
    '//',
    '// Usage:',
    '//   const root = spawnCustomItem("Monster", { position: { x: 8, y: 0, z: 8 } })',
    '//   // To despawn: engine.removeEntityWithChildren(root)',
    '//',
    '// IMPORTANT: Call initAssetPacks() before spawnCustomItem() if your Custom Items',
    '// contain Smart Item components (Actions, Triggers, States).',
    '',
    "import type { Entity } from '@dcl/sdk/ecs'",
    "import { engine } from '@dcl/sdk/ecs'",
    "import { spawnFromComposite } from '@dcl/asset-packs'",
    '',
  );

  if (entries.length === 0) {
    lines.push(
      '// No Custom Items found. Create one in the inspector and save the scene.',
      '',
      '/** Union of all Custom Item names. Currently empty — add Custom Items in the inspector. */',
      'export type CustomItemName = never',
      '',
      '/**',
      ' * Spawn a Custom Item by name.',
      ' * @returns the root Entity of the spawned item tree.',
      ' */',
      'export function spawnCustomItem(',
      '  _name: CustomItemName,',
      '  _options?: {',
      '    parent?: Entity',
      '    position?: { x: number; y: number; z: number }',
      '    rotation?: { x: number; y: number; z: number; w: number }',
      '    scale?: { x: number; y: number; z: number }',
      '  },',
      '): Entity {',
      "  throw new Error('spawnCustomItem: no Custom Items defined. Add Custom Items in the inspector.')",
      '}',
      '',
    );
    return lines.join('\n');
  }

  // Inline composite data constants
  for (const entry of entries) {
    lines.push(
      `// Custom Item: ${entry.displayName}`,
      `const _COMPOSITE_${entry.identifier} = ${JSON.stringify(entry.composite, null, 2)} as const`,
      '',
    );
  }

  // Registry object
  lines.push('const _CUSTOM_ITEMS = {');
  for (const entry of entries) {
    lines.push(
      `  '${entry.displayName}': {`,
      `    id: '${entry.id}',`,
      `    composite: _COMPOSITE_${entry.identifier},`,
      `  },`,
    );
  }
  lines.push('} as const', '');

  // CustomItemName type
  const nameUnion = entries.map(e => `'${e.displayName}'`).join(' | ');
  lines.push(
    '/** Union of all Custom Item names defined in this scene. */',
    `export type CustomItemName = ${nameUnion}`,
    '',
  );

  // spawnCustomItem function
  lines.push(
    '/**',
    ' * Spawn a Custom Item by name, returning the root Entity of the spawned tree.',
    ' *',
    ' * @param name - The display name of the Custom Item (type-checked at compile time).',
    ' * @param options - Optional spawn configuration.',
    ' * @returns The root Entity. Use `engine.removeEntityWithChildren(root)` to despawn.',
    ' *',
    ' * @example',
    ' * ```ts',
    ' * const root = spawnCustomItem("Monster", { position: { x: 8, y: 0, z: 8 } })',
    ' * // Later: engine.removeEntityWithChildren(root)',
    ' * ```',
    ' */',
    'export function spawnCustomItem(',
    '  name: CustomItemName,',
    '  options?: {',
    '    parent?: Entity',
    '    position?: { x: number; y: number; z: number }',
    '    rotation?: { x: number; y: number; z: number; w: number }',
    '    scale?: { x: number; y: number; z: number }',
    '  },',
    '): Entity {',
    '  const item = _CUSTOM_ITEMS[name]',
    '  return spawnFromComposite(engine, item.composite as any, options)',
    '}',
    '',
  );

  return lines.join('\n');
}

/**
 * Generate `src/custom-items.gen.ts` from the current Custom Items on disk.
 *
 * Called automatically when Custom Items are created, renamed, or deleted,
 * and on every composite save (scene open / Ctrl+S).
 */
export async function generateCustomItemsFile(
  fs: FileSystemInterface,
  customDir: string = withAssetDir(DIRECTORY.CUSTOM),
): Promise<void> {
  try {
    const entries = await readCustomItems(fs, customDir);
    const fileContent = buildFileContent(entries);

    // Skip write if content is unchanged (avoids unnecessary file-system events)
    const outputPath = CUSTOM_ITEMS_GEN_PATH;
    if (await fs.existFile(outputPath)) {
      const existing = (await fs.readFile(outputPath)).toString('utf-8');
      if (existing === fileContent) return;
    }

    await fs.writeFile(outputPath, Buffer.from(fileContent, 'utf-8'));
  } catch (err) {
    console.error('generateCustomItemsFile: failed to generate custom-items.gen.ts:', err);
  }
}
