import { describe, it, expect, beforeEach } from 'vitest';
import type { FileSystemInterface } from '../../../data-layer/types';
import { createInMemoryStorage } from '../../../logic/storage/in-memory';
import { createFileSystemInterface } from '../../../logic/file-system-interface';
import { generateCustomItemsFile, CUSTOM_ITEMS_GEN_PATH } from './generate-custom-items';

const SIMPLE_COMPOSITE = {
  version: 1,
  components: [
    {
      name: 'core::Transform',
      data: {
        '512': {
          json: {
            position: { x: 0, y: 0, z: 0 },
            rotation: { x: 0, y: 0, z: 0, w: 1 },
            scale: { x: 1, y: 1, z: 1 },
          },
        },
      },
    },
    {
      name: 'core::GltfContainer',
      data: {
        '512': {
          json: {
            src: '{assetPath}/model.glb',
          },
        },
      },
    },
  ],
};

function makeFs(files: Record<string, Buffer>): FileSystemInterface {
  return createFileSystemInterface(createInMemoryStorage(files));
}

describe('generateCustomItemsFile', () => {
  describe('when there are no custom items', () => {
    let fs: FileSystemInterface;

    beforeEach(() => {
      fs = makeFs({});
    });

    it('should generate a file with CustomItemName = never', async () => {
      await generateCustomItemsFile(fs, 'assets/custom');
      const content = (await fs.readFile(CUSTOM_ITEMS_GEN_PATH)).toString('utf-8');
      expect(content).toContain('export type CustomItemName = never');
    });

    it('should include auto-generated header comment', async () => {
      await generateCustomItemsFile(fs, 'assets/custom');
      const content = (await fs.readFile(CUSTOM_ITEMS_GEN_PATH)).toString('utf-8');
      expect(content).toContain('Auto-generated by the Decentraland Creator Hub');
    });

    it('should include despawn documentation', async () => {
      await generateCustomItemsFile(fs, 'assets/custom');
      const content = (await fs.readFile(CUSTOM_ITEMS_GEN_PATH)).toString('utf-8');
      expect(content).toContain('engine.removeEntityWithChildren');
    });
  });

  describe('when there is one custom item', () => {
    let fs: FileSystemInterface;

    beforeEach(() => {
      fs = makeFs({
        'assets/custom/monster_1/data.json': Buffer.from(
          JSON.stringify({ id: 'abc-123', name: 'Monster', category: 'custom', tags: [] }),
        ),
        'assets/custom/monster_1/composite.json': Buffer.from(
          JSON.stringify(SIMPLE_COMPOSITE),
        ),
      });
    });

    it('should generate a file with the item name in the union type', async () => {
      await generateCustomItemsFile(fs, 'assets/custom');
      const content = (await fs.readFile(CUSTOM_ITEMS_GEN_PATH)).toString('utf-8');
      expect(content).toContain("export type CustomItemName = 'Monster'");
    });

    it('should replace {assetPath} with the actual folder path', async () => {
      await generateCustomItemsFile(fs, 'assets/custom');
      const content = (await fs.readFile(CUSTOM_ITEMS_GEN_PATH)).toString('utf-8');
      expect(content).not.toContain('{assetPath}');
      expect(content).toContain('assets/custom/monster_1');
    });

    it('should export a spawnCustomItem function', async () => {
      await generateCustomItemsFile(fs, 'assets/custom');
      const content = (await fs.readFile(CUSTOM_ITEMS_GEN_PATH)).toString('utf-8');
      expect(content).toContain('export function spawnCustomItem(');
    });

    it('should import spawnFromComposite from @dcl/asset-packs', async () => {
      await generateCustomItemsFile(fs, 'assets/custom');
      const content = (await fs.readFile(CUSTOM_ITEMS_GEN_PATH)).toString('utf-8');
      expect(content).toContain("import { spawnFromComposite } from '@dcl/asset-packs'");
    });
  });

  describe('when there are multiple custom items', () => {
    let fs: FileSystemInterface;

    beforeEach(() => {
      fs = makeFs({
        'assets/custom/monster_1/data.json': Buffer.from(
          JSON.stringify({ id: 'id-1', name: 'Monster', category: 'custom', tags: [] }),
        ),
        'assets/custom/monster_1/composite.json': Buffer.from(
          JSON.stringify(SIMPLE_COMPOSITE),
        ),
        'assets/custom/chest_2/data.json': Buffer.from(
          JSON.stringify({ id: 'id-2', name: 'Chest', category: 'custom', tags: [] }),
        ),
        'assets/custom/chest_2/composite.json': Buffer.from(
          JSON.stringify(SIMPLE_COMPOSITE),
        ),
      });
    });

    it('should include all item names in the union type', async () => {
      await generateCustomItemsFile(fs, 'assets/custom');
      const content = (await fs.readFile(CUSTOM_ITEMS_GEN_PATH)).toString('utf-8');
      expect(content).toContain("'Monster'");
      expect(content).toContain("'Chest'");
      expect(content).toContain('export type CustomItemName =');
    });

    it('should include composites for each item', async () => {
      await generateCustomItemsFile(fs, 'assets/custom');
      const content = (await fs.readFile(CUSTOM_ITEMS_GEN_PATH)).toString('utf-8');
      expect(content).toContain('assets/custom/monster_1');
      expect(content).toContain('assets/custom/chest_2');
    });
  });

  describe('when names would produce duplicate identifiers', () => {
    let fs: FileSystemInterface;

    beforeEach(() => {
      // "My Monster" and "My_Monster" both sanitize to "My_Monster"
      fs = makeFs({
        'assets/custom/item_1/data.json': Buffer.from(
          JSON.stringify({ id: 'id-1', name: 'My Monster', category: 'custom', tags: [] }),
        ),
        'assets/custom/item_1/composite.json': Buffer.from(JSON.stringify(SIMPLE_COMPOSITE)),
        'assets/custom/item_2/data.json': Buffer.from(
          JSON.stringify({ id: 'id-2', name: 'My_Monster', category: 'custom', tags: [] }),
        ),
        'assets/custom/item_2/composite.json': Buffer.from(JSON.stringify(SIMPLE_COMPOSITE)),
      });
    });

    it('should generate unique composite constants', async () => {
      await generateCustomItemsFile(fs, 'assets/custom');
      const content = (await fs.readFile(CUSTOM_ITEMS_GEN_PATH)).toString('utf-8');
      // One will be _COMPOSITE_My_Monster and the other _COMPOSITE_My_Monster_1
      expect(content).toContain('_COMPOSITE_My_Monster');
      expect(content).toContain('_COMPOSITE_My_Monster_1');
      // They must be distinct (no repeated definition for the same identifier).
      // Use " =" suffix to avoid matching _COMPOSITE_My_Monster_1 as a false positive.
      const exactConstMatches = content.match(/const _COMPOSITE_My_Monster =/g) ?? [];
      expect(exactConstMatches.length).toBe(1);
    });
  });

  describe('idempotency', () => {
    let fs: FileSystemInterface;

    beforeEach(() => {
      fs = makeFs({
        'assets/custom/monster_1/data.json': Buffer.from(
          JSON.stringify({ id: 'abc', name: 'Monster', category: 'custom', tags: [] }),
        ),
        'assets/custom/monster_1/composite.json': Buffer.from(JSON.stringify(SIMPLE_COMPOSITE)),
      });
    });

    it('should not overwrite the file if content is unchanged', async () => {
      await generateCustomItemsFile(fs, 'assets/custom');
      const content1 = (await fs.readFile(CUSTOM_ITEMS_GEN_PATH)).toString('utf-8');

      // Write a sentinel to detect if the file gets rewritten
      await fs.writeFile(CUSTOM_ITEMS_GEN_PATH, Buffer.from(content1));

      await generateCustomItemsFile(fs, 'assets/custom');
      const content2 = (await fs.readFile(CUSTOM_ITEMS_GEN_PATH)).toString('utf-8');

      expect(content1).toEqual(content2);
    });
  });

  describe('when a custom item folder is missing composite.json', () => {
    it('should skip the incomplete item gracefully', async () => {
      const fs = makeFs({
        'assets/custom/incomplete_1/data.json': Buffer.from(
          JSON.stringify({ id: 'id-x', name: 'Incomplete', category: 'custom', tags: [] }),
        ),
        // no composite.json
        'assets/custom/monster_1/data.json': Buffer.from(
          JSON.stringify({ id: 'id-1', name: 'Monster', category: 'custom', tags: [] }),
        ),
        'assets/custom/monster_1/composite.json': Buffer.from(JSON.stringify(SIMPLE_COMPOSITE)),
      });

      await generateCustomItemsFile(fs, 'assets/custom');
      const content = (await fs.readFile(CUSTOM_ITEMS_GEN_PATH)).toString('utf-8');

      // Valid item should be present
      expect(content).toContain("'Monster'");
      // Incomplete item should be skipped
      expect(content).not.toContain("'Incomplete'");
    });
  });
});
