name: AI Pull Request Review

on:
  workflow_dispatch:
    inputs:
      force_refresh:
        description: 'Force refresh analysis (ignore cache)'
        required: false
        default: 'false'
        type: boolean
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created, edited]

jobs:
  ai-review:
    if: |
      (github.event_name == 'pull_request' && github.event.label.name == 'ai-review') ||
      (github.event_name == 'issue_comment' && 
       github.event.issue.pull_request &&
       contains(github.event.comment.body, 'ai-review'))
    uses: decentraland/actions/.github/workflows/ai-pr-review.yml@feat/smart-pr
    with:
      script_branch: feat/smart-pr
    secrets: inherit