name: AI Pull Request Review

on:
  workflow_dispatch:
    inputs:
      force_refresh:
        description: 'Force refresh analysis (ignore cache)'
        required: false
        default: 'false'
        type: boolean
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [labeled]

jobs:
  ai-review:
    if: github.event.label.name == 'ai-review' || github.event_name == 'workflow_dispatch' || github.event_name == 'issue_comment'
    uses: decentraland/actions/.github/workflows/ai-pr-review.yml@feat/smart-pr
    with:
      script_branch: feat/smart-pr
    secrets: inherit