name: AI Pull Request Review

on:
  workflow_dispatch:
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created, edited]

jobs:
  check-member:
    if: github.event_name == 'issue_comment' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      is-member: ${{ steps.check.outputs.is-member }}
    steps:
      - name: Check if user is organization member
        id: check
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            USERNAME="${{ github.event.sender.login }}"
          else
            USERNAME="${{ github.event.comment.user.login }}"
          fi
          ORG="decentraland"
          
          # Check if user is a member of the organization
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/orgs/$ORG/members/$USERNAME")
          
          if echo "$RESPONSE" | grep -q '"login"'; then
            echo "is-member=true" >> $GITHUB_OUTPUT
          else
            echo "is-member=false" >> $GITHUB_OUTPUT
          fi

  ai-review:
    needs: check-member
    if: |
      needs.check-member.outputs.is-member == 'true' && (
        (github.event_name == 'pull_request' && github.event.label.name == 'ai-review') ||
        (github.event_name == 'issue_comment' && 
         github.event.issue.pull_request &&
         github.event.comment.body == 'ai-review' &&
         github.event.comment.user.type == 'User')
      )
    uses: decentraland/actions/.github/workflows/ai-pr-review.yml@main
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}