name: Drop pre-release
on:
  workflow_call:
    inputs:
      dry-run:
        description: 'Compiles the app but not upload artifacts to distribution server'
        default: false
        required: false
        type: boolean
concurrency:
  group: drop-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: 'bash'
jobs:
  drop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Delete prereleases
        if: ${{ github.ref == 'refs/heads/main' && !inputs.dry-run }}
        uses: ./.github/actions/delete-prereleases
        with:
          pattern: '^[0-9]+\.[0-9]+\.[0-9]+$'
          dry_run: 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
