name: Inspector
on:
  workflow_call:
    outputs:
      s3_bucket_key:
        description: "S3 bucket key for the published Inspector package"
        value: ${{ jobs.publish.outputs.s3_bucket_key }}
      version:
        description: "Version of the Inspector package"
        value: ${{ jobs.version.outputs.version }}
      changed:
        description: "Whether the version of the Inspector package has changed"
        value: ${{ jobs.version.outputs.changed }}

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      changed: ${{ steps.version.outputs.changed }}
      version: ${{ steps.version.outputs.version }}
      previous_version: ${{ steps.version.outputs.previous_version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump release version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "@dcl/inspector@"
          version_format: ${major}.${minor}.${patch}
          major_pattern: "/^(major|breaking).+/"
          minor_pattern: "/^(minor|feat).+/"
          bump_each_commit: false
          bump_each_commit_patch_pattern: "/^(patch|fix).+/"
          search_commit_body: true
          user_format_type: "json"
          change_path: "packages/inspector"

  publish:
    runs-on: ubuntu-latest
    needs: [version]
    if: ${{ needs.version.outputs.changed == 'true' }}
    permissions:
      pages: write
      contents: read
      id-token: write
    outputs:
      s3_bucket_key: ${{ steps.s3-upload.outputs.s3-key }}
      preview_url: ${{ steps.set-preview-url.outputs.preview_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: install
        run: make install

      - name: protoc
        run: make protoc

      - name: build
        run: make build-inspector

      - name: npm version
        working-directory: ./packages/inspector
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            VERSION="${{ needs.version.outputs.version }}"
          else
            VERSION="${{ needs.version.outputs.version }}-commit-${{ github.sha }}"
          fi
          npm version "$VERSION" --force --no-git-tag-version --allow-same-version

      - name: npm pack
        working-directory: ./packages/inspector
        id: npm-pack
        run: |
          PACK_OUTPUT=$(npm pack --json)
          PACK_FILENAME=$(echo "$PACK_OUTPUT" | jq -r '.[0].filename')
          echo "pack-filename=$PACK_FILENAME" >> $GITHUB_OUTPUT

      - name: upload package to S3
        uses: ./.github/actions/s3-upload
        id: s3-upload
        with:
          file-path: ./packages/inspector/${{ steps.npm-pack.outputs.pack-filename }}
          bucket: ${{ secrets.SDK_TEAM_S3_BUCKET }}
          region: ${{ secrets.SDK_TEAM_AWS_REGION }}
          prefix: 'creator-hub/branch/${{ github.head_ref || github.ref }}/@dcl/inspector'
          aws-access-key-id: ${{ secrets.SDK_TEAM_AWS_ID }}
          aws-secret-access-key: ${{ secrets.SDK_TEAM_AWS_SECRET }}
          content-type: 'application/gzip'
          acl: 'public-read'
          cache-control: 'max-age=0,private'

      - name: sanitize branch
        id: sanitize-branch
        run: |
          branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          safe_branch=${branch//\//-}  # replace / with -
          echo "safe_branch=$safe_branch" >> $GITHUB_OUTPUT

      - name: prepare deployment folder ("hack" for subpaths in github pages url)
        run: |
          safe_branch=${{ steps.sanitize-branch.outputs.safe_branch }}
          mkdir -p ./deploy/inspector/$safe_branch
          cp -r ./packages/inspector/public/* ./deploy/inspector/$safe_branch/

      - name: upload inspector artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy
          name: inspector

      - name: deploy to gh-pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: inspector

      - name: set preview url
        id: set-preview-url
        run: |
          safe_branch=${{ steps.sanitize-branch.outputs.safe_branch }}
          echo "preview_url=https://decentraland.github.io/creator-hub/inspector/$safe_branch" >> $GITHUB_OUTPUT

      - name: publish to npm registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ./.github/actions/npm-publish
        id: npm-publish
        with:
          working-directory: ./packages/inspector
          npm-token: ${{ secrets.NPM_TOKEN }}
          initial-tag: 'latest'
          access: 'public'

  notify:
    needs: [version, publish]
    if: ${{ github.event.pull_request.number && needs.version.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Test @dcl/inspector package

      - name: create or update comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            # Test @dcl/inspector package

            - Preview: [link](${{ needs.publish.outputs.preview_url }})
            - Install via NPM:
              ```bash
              npm install "${{ secrets.SDK_TEAM_S3_BASE_URL }}/${{ needs.publish.outputs.s3_bucket_key }}"
              ```
          edit-mode: replace

  release:
    needs: [version, publish]
    if: ${{ needs.version.outputs.changed == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: generate release notes
        if: ${{ github.ref == 'refs/heads/main' }}
        id: release_notes
        uses: ./.github/actions/generate-release-notes
        with:
          previous_version: ${{ needs.version.outputs.previous_version }}
          current_version: ${{ needs.version.outputs.version }}
          paths: 'packages/inspector'
          section_names: 'Inspector Changes'
          release_title: '@dcl/inspector'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: '@dcl/inspector@'

      - name: update release description
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: ./.github/actions/update-release-description
        with:
          tag_name: "@dcl/inspector@${{ needs.version.outputs.version }}"
          release_notes: ${{ steps.release_notes.outputs.release_notes }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_if_not_exists: true
          prerelease: true
