name: Lint
on:
  workflow_dispatch:
  push:
    paths:
      - '**/*.js'
      - '**/*.mjs'
      - '**/*.cjs'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.mts'
      - '**/*.cts'
      - '**/*.tsx'
  pull_request:
    paths:
      - '**/*.js'
      - '**/*.mjs'
      - '**/*.cjs'
      - '**/*.jsx'
      - '**/*.ts'
      - '**/*.mts'
      - '**/*.cts'
      - '**/*.tsx'

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - run: npm ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - run: npm run lint --if-present

  # This job just check code style for in-template contributions.
  code-style:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - run: npm i prettier
      - run: |
          # Get the list of modified files
          MODIFIED_FILES=$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(js|mjs|cjs|jsx|ts|mts|cts|tsx)$')

          # Exit if there are no modified files to check
          if [ -z "$MODIFIED_FILES" ]; then
            echo "No modified files to verify."
            exit 0
          fi

          # Run Prettier's check mode on the modified files
          echo "$MODIFIED_FILES" | xargs npx prettier --check
