name: Typechecking
on: [ workflow_call ]

concurrency:
  group: typechecking-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  typescript:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/setup
        id: setup
        with:
          cache-protoc: 'true'
          cache-asset-packs-build: 'true'

      - name: install
        if: steps.setup.outputs.node-modules-cache-hit != 'true'
        run: make install
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: '1'

      - run: make protoc
      - name: build asset-packs
        if: steps.setup.outputs.asset-packs-build-cache-hit != 'true'
        run: make build-asset-packs
      - run: npm run typecheck --if-present
